# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django_celery_fulldbresult.models
import djcelery.picklefield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResultMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=191, unique=True, verbose_name='task id')),
                ('task', models.CharField(max_length=191, verbose_name='task name')),
                ('args', models.TextField(blank=True, default='[]', help_text='JSON encoded positional arguments', verbose_name='arguments')),
                ('kwargs', models.TextField(blank=True, default='{}', help_text='JSON encoded keyword arguments', verbose_name='keyword arguments')),
                ('hostname', models.CharField(blank=True, max_length=191, null=True, verbose_name='hostname')),
                ('exchange', models.CharField(blank=True, default=None, max_length=191, null=True, verbose_name='exchange')),
                ('routing_key', models.CharField(blank=True, default=None, max_length=191, null=True, verbose_name='routing key')),
                ('eta', models.DateTimeField(blank=True, null=True, verbose_name='eta')),
                ('expires', models.DateTimeField(blank=True, null=True, verbose_name='expires')),
                ('status', models.CharField(choices=[(b'FAILURE', b'FAILURE'), (b'PENDING', b'PENDING'), (b'RECEIVED', b'RECEIVED'), (b'RETRY', b'RETRY'), (b'REVOKED', b'REVOKED'), ('SCHEDULED', 'SCHEDULED'), ('SCHEDULED_SENT', 'SCHEDULED_SENT'), (b'STARTED', b'STARTED'), (b'SUCCESS', b'SUCCESS')], default=b'PENDING', max_length=50, verbose_name='state')),
                ('scheduled_id', models.UUIDField(blank=True, null=True)),
                ('result', django_celery_fulldbresult.models.PickledOrJSONObjectField(default=None, editable=False, null=True)),
                ('date_submitted', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('date_done', models.DateTimeField(auto_now=True, verbose_name='done at')),
                ('traceback', models.TextField(blank=True, null=True, verbose_name='traceback')),
                ('hidden', models.BooleanField(db_index=True, default=False, editable=False)),
                ('meta', djcelery.picklefield.PickledObjectField(default=None, editable=False, null=True)),
            ],
            options={
                'db_table': 'celery_taskresultmeta',
                'verbose_name': 'task state',
                'verbose_name_plural': 'task states',
            },
        ),
    ]
